name: Build with KernelSU

on:
  workflow_dispatch:
    inputs:
      KSU_BRANCH:
        description: '请选择KernelSU分支'
        required: true
        type: choice
        options:
          - 'KernelSU'
          - 'KernelSU-Next'
          - 'ReSukiSU'
          - 'NO KernrlSU'
        default: KernelSU-Next
        
      SuSFS_STAT:
        description: 'SuSFS'
        required: true
        type: choice
        options:
          - 'YES'
          - 'NO'
        default: 'YES'
      SSG_IO:
        description: 'SSG IO调度'
        required: true
        type: choice
        options:
          - 'YES'
          - 'NO'
      default: 'YES'
      MFY_STAT:
        description: 'Mountify支持'
        required: true
        type: choice
        options:
          - 'YES'
          - 'NO'
        default: 'YES'
      IPS_STAT:
        description: 'Netfilter / IPSET'
        required: true
        type: choice
        options:
          - 'YES'
          - 'NO'
        default: 'YES'
      BBR_STAT:
        description: 'BBR 拥塞控制'
        required: true
        type: choice
        options:
          - 'YES'
          - 'NO'
        default: 'YES'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
